### ISSUE TITLE
치명적인 오류

### ISSUE THREAD

**Issue by mark3236** [y0s30b/mp17arm_interrupt#1]
개발자가 너무 4차원임

**Comment by mark3236** [comment]
> 잘생김
아니, 못생김

**Comment by y0s30b** [comment]
@mark3236 
![image](https://cloud.githubusercontent.com/assets/25506458/25447023/77f41c52-2aee-11e7-89b1-779ea9ccc867.png) (img src: http://www.foundalis.com/phy/4Dsphere.htm)
